import { PendingProducer } from '../../services/app';

const data: PendingProducer[] = [
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e4',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e3',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e2',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e1',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e0',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e9',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e8',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
  {
    id: '730e0a38-3ae1-464d-a784-abaf296766e7',
    certificationType: 'IN CONVERSION',
    name: 'IAGO FAGUNDES',
    email: 'iago.fagundes@outlook.com',
    phone: '75999503472',
    address: {
      state: 'ESTADO',
      city: 'CIDADE',
      district: 'BAIRRO',
      street: 'RUA',
      zipCode: '49100000',
      complement: 'complement',
      lat: null,
      long: null,
      number: 's/n',
    },
  },
];

export default data;
